name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Configure CMake (with clang-tidy)
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER=clang++-14 \
            -DCMAKE_C_COMPILER=clang-14 \
            -Dlibcarma_RUN_CLANG_TIDY=TRUE \
            .

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER=clang++-14 \
            -DCMAKE_C_COMPILER=clang-14 \
            .

      - name: Build project
        run: |
          cmake --build build

      - name: Run CTest
        run: |
          ctest --test-dir build
