name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Configure CMake (with clang-tidy)
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER=clang++-14 \
            -DCMAKE_C_COMPILER=clang-14 \
            -Dlibcarma_RUN_CLANG_TIDY=TRUE \
            .
