name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        path: src/libcarma

      - name: Build libraries (with clang-tidy enabled)
        run: |
          colcon build \
            --cmake-args \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CXX_STANDARD=17 \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_CXX_EXTENSIONS=OFF \
              -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-extra-arg=-std=c++17" \
              -DCMAKE_C_STANDARD=11 \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_C_EXTENSIONS=OFF \
              -DCMAKE_C_CLANG_TIDY=clang-tidy \
              -Dlibcarma_BUILD_INSTALL=TRUE \
              -Dlibcarma_BUILD_TESTS=TRUE

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        path: src/libcarma

      - name: Build libraries
        run: |
          colcon build \
            --cmake-args \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CXX_STANDARD=17 \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_CXX_EXTENSIONS=OFF \
              -DCMAKE_C_STANDARD=11 \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_C_EXTENSIONS=OFF \
              -Dlibcarma_BUILD_INSTALL=TRUE \
              -Dlibcarma_BUILD_TESTS=TRUE

      - name: Run tests
        run: |
          colcon test
